COMPILE | -DAPP=S2SWA -DCCPP_SUITES=FV3_GFS_v16_coupled_nsstNoahmpUGWPv1,FV3_GFS_v17_coupled_p8                                   | - wcoss_cray                            | fv3 |
RUN     | cpld_control_p8                                                                                                         | - wcoss_cray                            | fv3 |
RUN     | cpld_2threads_p8                                                                                                        | - wcoss_cray                            |     |
RUN     | cpld_decomp_p8                                                                                                          | - wcoss_cray jet.intel                  |     |
RUN     | cpld_mpi_p8                                                                                                             | - wcoss_cray                            |     |

RUN     | cpld_bmark_p8                                                                                                           | - wcoss_cray jet.intel                  | fv3 |


