#!/bin/sh
#SBATCH -J REPLAY
#SBATCH --time=04:00:00
#SBATCH -o %x.o%j
#SBATCH --ntasks=1
#SBATCH --exclusive #may mean use all memory
#SBATCH -A marine-cpu
# for HPSS
##SBATCH --partition=service


##PBS -j oe
##PBS -N REPLAY_CICE
##PBS -A GEFS-DEV
##PBS -q dev_transfer
##PBS -l select=1:ncpus=1:mem=5GB
##PBS -l walltime=01:00:00


~/ANALYSIS/REPLAY_DEMO/REPLAY_MAPS.py
#~/ANALYSIS/REPLAY_DEMO/REPLAY_COMPARE.py
#~/ANALYSIS/REPLAY_DEMO/CICE_data_ctl.sh
