#!/bin/sh
#PBS -N albsni_d
#PBS -j oe
#PBS -A GEFS-DEV
#PBS -q dev_transfer
#PBS -l select=1:ncpus=1:mem=5GB
#PBS -l walltime=01:00:00
#PBS -V
set -xu
# vars are Tsfc_d, hs_d, hi_d, snow_d, albsni_d, aice_d


~/ANALYSIS/REPLAY_DEMO/CICE_data.sh albsni_d
