#!/bin/sh -l
#SBATCH -J NPB_transfer
#SBATCH --time=04:00:00
#SBATCH -o %x.o%j
#SBATCH --ntasks=1
#SBATCH --exclusive #may mean use all memory
#SBATCH -A marine-cpu
#SBATCH --partition=service #for HPSS

~/ANALYSIS/DATA_PARSE/transfer_job
python nsidc-download_NSIDC-0051.002_2022-12-22.py
