#!/bin/sh -l
#SBATCH -J AMS
#SBATCH --time=04:00:00
#SBATCH -o %x.o%j
#SBATCH --ntasks=1
#SBATCH --exclusive #may mean use all memory
#SBATCH -A marine-cpu
# for HPSS
##SBATCH --partition=service

TOPDIR=/home/Neil.Barton/ANALYSIS/AMS2023/GRAB_DATA
${TOPDIR}/wgrib2_TO_netcdf.sh TMP:1

#TOPDIR=/home/Neil.Barton/ANALYSIS/AMS2023/GRAB_DATA
#${TOPDIR}/wgrib2_TO_netcdf.sh DSWRF
#${TOPDIR}/wgrib2_TO_netcdf.sh CSDSF
#${TOPDIR}/calc_CRF.sh L G
#${TOPDIR}/calc_CRF.sh L T

#TOPDIR=/home/Neil.Barton/ANALYSIS/AMS2023
#$TOPDIR/ufs_output_compare.py 
#f=DLWRF
#v=surface
#files=$( ls /scratch2/NCEPDEV/stmp3/Neil.Barton/UFS_OUTPUT/P8*/${f}.nc)
#$TOPDIR/ufs_output_compare.py -f $files -v ${f}_${v}

#TOPDIR=/home/Neil.Barton/ANALYSIS/GRAB_DATA
#files=$( ls /scratch2/NCEPDEV/stmp3/Neil.Barton/UFS_OUTPUT/P8T/WORKING_DIR/CICE_2*nc)
#${TOPDIR}/CICE_cat_netcdf.py -f ${files}

#cd /scratch2/NCEPDEV/stmp3/Neil.Barton/UFS_OUTPUT/P8T
#DATA_DIR=/scratch2/NCEPDEV/stmp3/Neil.Barton/UFS_OUTPUT/
