#!/bin/sh -l
#SBATCH -J NPBjob_card
#SBATCH --time=04:00:00
#SBATCH -o %x.o%j
#SBATCH --ntasks=1
#SBATCH --exclusive #may mean use all memory
#SBATCH -A marine-cpu
# for HPSS
##SBATCH --partition=service

cd /home/Neil.Barton/UFS
./CREATE-grid_spec_file.sh
