#!/bin/sh -l
#SBATCH -J NPBnetcdf
#SBATCH --time=02:00:00
#SBATCH -o %x.o%j
#SBATCH --ntasks=1
#SBATCH --exclusive #may mean use all memory
#SBATCH -A marine-cpu
# for HPSS
##SBATCH --partition=service

TOPDIR=/home/Neil.Barton/ANALYSIS/GRAB_DATA
files=$( ls /scratch2/NCEPDEV/stmp3/Neil.Barton/UFS_OUTPUT/P8T/CICE_2*nc)
${TOPDIR}/cat_netcdf.py -f ${files}
#cd /scratch2/NCEPDEV/stmp3/Neil.Barton/UFS_OUTPUT/P8T
#ncwa -a time -t 2 TEST.nc M_TEST.nc

