#!/bin/sh
#PBS -N WCOSS2_TRANSFER
#PBS -j oe
#PBS -A GEFS-DEV
#PBS -q dev_transfer
#PBS -l select=1:ncpus=1:mem=5GB
#PBS -l walltime=01:00:00
#PBS -V
set -xu

cd /lfs/h2/emc/ens/noscrub/neil.barton/ICs/
htar -xvf /NCEPDEV/emc-marine/1year/Neil.Barton/GW_TEST.tar 
#~/REPLAY_ICS.sh

