#!/bin/sh -l
#SBATCH --job-name="transfer"
#SBATCH -o %x.o%j
#SBATCH --time=08:00:00
#SBATCH --ntasks=1
#SBATCH --account=sfs-cpu
#SBATCH --qos=hpss
#SBATCH --partition=dtn_f5_f6
#SBATCH --constraint=f6


/gpfs/f6/sfs-emc/scratch/Neil.Barton/RUNS/UFS/htar.sh
