#!/bin/sh -l
#SBATCH -J TRANSFER
#SBATCH --time=04:00:00
#SBATCH -o %x.o%j
#SBATCH --ntasks=1
#SBATCH --exclusive #may mean use all memory
#SBATCH -A marine-cpu
#SBATCH --partition=service #for HPSS
wget https://noaa-ufs-gefsv13replay-pds.s3.amazonaws.com/1998/02/1998022006/fv_core.res.tile1.nc -O 19980220.030000.fv_core.res.tile1.nc


